---
title: "Lab 7 Assignment: Group 08"
format: 
  html:
    embed-resources: true
editor: visual
---

# Group Assignment

## Load libraries

```{r}
#| message: false
library(tidyverse)
library(broom)
library(patchwork)
```

## Load data

```{r}
raw_dir <- "data/_raw/"
data_file <- "gravier.RData"
data_loc <- "https://github.com/ramhiser/datamicroarray/raw/master/data/"

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir)
}
if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
}
load(file = str_c(raw_dir, data_file))
```

Clean data and Mutate with Metastasis as selector

```{r}
gravier_clean <- gravier |>
  bind_cols() |>
  as_tibble() |> 
  write_tsv("data/02_gravier_clean.tsv.gz")

gravier_clean_aug <- gravier_clean |>
  mutate(y = case_when(y == "poor" ~ 1,
                       y == "good" ~ 0)) |> 
  relocate(early_metastasis = y) |> 
  write_tsv("data/03_gravier_clean_aug.tsv.gz")
```

## Compute PCA

```{r}
pca_fit <- gravier_clean_aug |>  
  select(where(is.numeric)) |>  # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data
```

### Plot PC1 vs PC2

```{r}
p1 <- pca_fit |> 
  augment(gravier_clean_aug) |> 
  ggplot(
    aes(.fittedPC1,
        .fittedPC2,
        color = as.factor(early_metastasis))
  ) + 
  geom_point()  +
  scale_color_manual(
    name="Metastasis state",
    labels=c("Good", "Poor"),
    values=c("darkblue", "darkorange")
  ) +
  labs(x = "PC1", y = "PC2") +
  theme_minimal()

p2 <- pca_fit |> 
  augment(gravier_clean_aug) |> 
  ggplot(
    aes(.fittedPC1,
        .fittedPC3,
        color = as.factor(early_metastasis))
  ) + 
  geom_point()  +
  scale_color_manual(
    name="Metastasis state",
    labels=c("Good", "Poor"),
    values=c("darkblue", "darkorange")
  ) +
  labs(x = "PC1", y = "PC3") +
  theme_minimal()

p3 <- pca_fit |> 
  augment(gravier_clean_aug) |> 
  ggplot(
    aes(.fittedPC2,
        .fittedPC3,
        color = as.factor(early_metastasis))
  ) + 
  geom_point()  +
  scale_color_manual(
    name="Metastasis state",
    labels=c("Good", "Poor"),
    values=c("darkblue", "darkorange")
  ) +
  labs(x = "PC2", y = "PC3") +
  theme_minimal()

p4 <- pca_fit |> 
  augment(gravier_clean_aug) |> 
  ggplot(
    aes(.fittedPC1,
        .fittedPC4,
        color = as.factor(early_metastasis))
  ) + 
  geom_point()  +
  scale_color_manual(
    name="Metastasis state",
    labels=c("Good", "Poor"),
    values=c("darkblue", "darkorange")
  ) +
  labs(x = "PC1", y = "PC4") +
  theme_minimal()

p1 + p2 + p3 + p4 |> wrap_plots()
```

## Inspect principal components

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

```{r}

pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous() +
  scale_y_continuous(
    labels = scales::percent_format()) +
  theme_minimal()
```
